include:
  - local: .gitlab-ci-build.yml
    rules:
      - if: '$CI_PIPELINE_SOURCE == "api"'
  - local: .gitlab-ci-deploy.yml
    rules:
      - if: '$CI_PIPELINE_SOURCE == "schedule"'

workflow:
  rules:
    - if: '$CI_PIPELINE_SOURCE == "api"'
      when: always
    - if: '$CI_PIPELINE_SOURCE == "schedule"'
      when: always
    - when: never

# Empty job, as gitlab-ci requires at least one job
empty:
  stage: build
  script: exit 1
  rules:
    - when: never
