spec:
  inputs:
    source_short_sha:
      description: "The short SHA of the source commit the generated the image"
      required: true
      type: string


Deploy Image Alma 10:
  stage: build
  image: quay.io/skopeo/stable:latest
  when: manual
  variables:
    BUILDAH_FORMAT: docker
  script:
    - export DATE_TAG="$(date +%Y%m%d)" && echo "Date TAG --- $DATE_TAG"
    - skopeo login --username "$CI_REGISTRY_USER" --password "$CI_REGISTRY_PASSWORD" "$CI_REGISTRY"
    - skopeo copy "${CI_REGISTRY_IMAGE}/alma-10-build:$[[source_short_sha]]" "${CI_REGISTRY_IMAGE}/alma-10-build:latest"
    - skopeo copy "${CI_REGISTRY_IMAGE}/alma-10-build:$[[source_short_sha]]" "${CI_REGISTRY_IMAGE}/alma-10-build:${DATE_TAG}"

Deploy Image Windows 2025:
  stage: build
  image: quay.io/skopeo/stable:latest
  when: manual
  script:
    - export DATE_TAG="$(date +%Y%m%d)" && echo "Date TAG --- $DATE_TAG"
    - skopeo login --username "$CI_REGISTRY_USER" --password "$CI_REGISTRY_PASSWORD" "$CI_REGISTRY"
    - skopeo copy "${CI_REGISTRY_IMAGE}/win2025-build:$[[source_short_sha]]" "${CI_REGISTRY_IMAGE}/win2025-build:latest"
    - skopeo copy "${CI_REGISTRY_IMAGE}/win2025-build:$[[source_short_sha]]" "${CI_REGISTRY_IMAGE}/win2025-build:${DATE_TAG}"
