workflow:
  rules:
    - if: '$CI_PIPELINE_SOURCE == "api"'
      when: always
    - when: never

stages:
  - build
  - deploy

Image Alma 10:
  stage: build
  image: quay.io/buildah/stable
  variables:
    BUILDAH_FORMAT: docker
  script:
    - echo "$CI_REGISTRY_PASSWORD" | buildah login --username "$CI_REGISTRY_USER" --password-stdin "$CI_REGISTRY"
    - buildah bud --build-arg ICS_REPO_DEPS_TOKEN="$ICS_REPO_DEPS_TOKEN" --file "${CI_PROJECT_DIR}/alma-10/Dockerfile" --tag "${CI_REGISTRY_IMAGE}/alma-10-build:${CI_COMMIT_SHORT_SHA}" "${CI_PROJECT_DIR}/alma-10"
    - buildah push "${CI_REGISTRY_IMAGE}/alma-10-build:${CI_COMMIT_SHORT_SHA}"

Image Windows 2025:
  stage: build
  tags:
    - powershell-win2025
  script:
    - cd w2025
    - .\Create-DotEnv-File.ps1
    - docker login -u $env:CI_REGISTRY_USER -p $env:CI_REGISTRY_PASSWORD $env:CI_REGISTRY
    - docker build --no-cache -t $env:CI_REGISTRY_IMAGE/win2025-build:$env:CI_COMMIT_SHORT_SHA  .
    - docker push $env:CI_REGISTRY_IMAGE/win2025-build:$env:CI_COMMIT_SHORT_SHA

Deploy Image Alma 10:
  stage: deploy
  needs: [Image Alma 10]
  dependencies: []
  image: quay.io/skopeo/stable:latest
  when: manual
  variables:
    BUILDAH_FORMAT: docker
  script:
    - export DATE_TAG="$(date +%Y%m%d)" && echo "Date TAG --- $DATE_TAG"
    - skopeo login --username "$CI_REGISTRY_USER" --password "$CI_REGISTRY_PASSWORD" "$CI_REGISTRY"
    - skopeo copy "${CI_REGISTRY_IMAGE}/alma-10-build:$[[source_short_sha]]" "${CI_REGISTRY_IMAGE}/alma-10-build:latest"
    - skopeo copy "${CI_REGISTRY_IMAGE}/alma-10-build:$[[source_short_sha]]" "${CI_REGISTRY_IMAGE}/alma-10-build:${DATE_TAG}"

Deploy Image Windows 2025:
  stage: deploy
  needs: [Image Windows 2025]
  dependencies: []
  image: quay.io/skopeo/stable:latest
  when: manual
  script:
    - export DATE_TAG="$(date +%Y%m%d)" && echo "Date TAG --- $DATE_TAG"
    - skopeo login --username "$CI_REGISTRY_USER" --password "$CI_REGISTRY_PASSWORD" "$CI_REGISTRY"
    - skopeo copy "${CI_REGISTRY_IMAGE}/win2025-build:$[[source_short_sha]]" "${CI_REGISTRY_IMAGE}/win2025-build:latest"
    - skopeo copy "${CI_REGISTRY_IMAGE}/win2025-build:$[[source_short_sha]]" "${CI_REGISTRY_IMAGE}/win2025-build:${DATE_TAG}"
